export const cursos = [
  "Administração",
  "Análise e Desenvolvimento de Sistemas",
  "Arquitetura e Urbanismo",
  "Biomedicina",
  "Ciências Contábeis",
  "Ciências Econômicas",
  "Direito",
  "Educação Física",
  "Enfermagem",
  "Engenharia Civil",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Farmácia",
  "Fisioterapia",
  "Geografia",
  "História",
  "Jornalismo",
  "Letras - Português/Inglês",
  "Matemática",
  "Medicina",
  "Medicina Veterinária",
  "Nutrição",
  "Odontologia",
  "Pedagogia",
  "Psicologia",
  "Publicidade e Propaganda",
  "Sistemas de Informação",
  "Serviço Social",
  "Teologia"
];
